language: c 
sudo: required
services:
 - docker

cache:
  ccache: true

branches:
  only:
  - master

stages:
  - name: cmake
  - name: mpi
  - name: deps
  - name: env

jobs:
  fast_finish: true
  include:
    - stage: cmake
      env: DISTRO=ubuntu18 DOCKERHUB=true DEPLOY=yes
    - env: DISTRO=fedora30 DOCKERHUB=true DEPLOY=yes
    - env: DISTRO=centos8 DOCKERHUB=true DEPLOY=yes
    - stage: mpi
      env: DISTRO=ubuntu18 DOCKERHUB=true DEPLOY=yes
    - env: DISTRO=fedora30 DOCKERHUB=true DEPLOY=yes
    - env: DISTRO=centos8 DOCKERHUB=true DEPLOY=yes
    - stage: deps
      env: DISTRO=ubuntu18 DOCKERHUB=true DEPLOY=yes
    - env: DISTRO=fedora30 DOCKERHUB=true DEPLOY=yes
    - env: DISTRO=centos8 DOCKERHUB=true DEPLOY=yes
    - stage: env
      env: DISTRO=ubuntu18 DOCKERHUB=true DEPLOY=yes
    - env: DISTRO=fedora30 DOCKERHUB=true DEPLOY=yes
    - env: DISTRO=centos8 DOCKERHUB=true DEPLOY=yes

script:
  - if [[ ${TRAVIS_BRANCH} != master ]]; then TAG="${TAG}_${TRAVIS_BRANCH//[^a-zA-Z0-9]/_}"; fi
  - ls ${DISTRO}
  - mkdir ${HOME}/docker
  - cp -v ${DISTRO}/${TRAVIS_BUILD_STAGE_NAME} ${HOME}/docker/Dockerfile
  - if [[ ${TRAVIS_BUILD_STAGE_NAME} = cmake ]]; then
      cp -v ${DISTRO}/packages.yaml ${HOME}/docker/;
      cd config;
      cp -v mirrors.yaml ${HOME}/docker/;
      cp -v -R mirror ${HOME}/docker/;
      cp -v entrypoint.sh ${HOME}/docker/;
      travis_wait 50 docker build -t ${TRAVIS_REPO_SLUG}:${DISTRO}${TAG}_tmp ${HOME}/docker/;
    fi
  - if [[ ${TRAVIS_BUILD_STAGE_NAME} = mpi ]]; then
      travis_wait 50 docker build -t ${TRAVIS_REPO_SLUG}:${DISTRO}${TAG}_tmp ${HOME}/docker/;
    fi
  - if [[ ${TRAVIS_BUILD_STAGE_NAME} = deps ]]; then
      travis_wait 50 docker build -t ${TRAVIS_REPO_SLUG}:${DISTRO}${TAG}_tmp ${HOME}/docker/;
    fi
  - if [[ ${TRAVIS_BUILD_STAGE_NAME} = env ]]; then
      travis_wait 50 docker build -t ${TRAVIS_REPO_SLUG}:${DISTRO}${TAG} ${HOME}/docker/;
    fi

after_success:
  - shopt -s extglob && [[ ${TRAVIS_BRANCH} = @(master) ]] && DEPLOY=yes
  - if [[ ${DOCKERHUB} = true && ${DOCKER_USERNAME} && ${DOCKER_PASSWORD} && ${TRAVIS_PULL_REQUEST} == false && ${DEPLOY} ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      if [[ ${TRAVIS_BUILD_STAGE_NAME} = env ]]; then
        docker push "${TRAVIS_REPO_SLUG}:${DISTRO}${TAG}";
      else
        docker push "${TRAVIS_REPO_SLUG}:${DISTRO}${TAG}_tmp";
      fi
   fi
